[package]
name = "dirigera"
description = "Manage your IKEA Trådfri devices with Rust"
version = "0.3.0"
edition = "2021"
authors = ["Simon Sawert<simon@sawert.se>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bombsimon/dirigera-rs"
repository = "https://github.com/bombsimon/dirigera-rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
http = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

hyper-rustls = "0.27"
rustls = { version = "0.23" }
hyper = { version = "1.9", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"

# Dependencies needed to run the binary to generate a token. Can be skipped if
# already obtained token or after token is obtained.
tokio = { version = "1.52", features = ["full"], optional = true }
toml = { version = "1.1", optional = true }
pkce = { version = "0.2", optional = true }
url = { version = "2.5", optional = true }
reqwest = { version = "0.13", features = ["json"], optional = true }

[dev-dependencies]
rand = "0.10"

[features]
default = []
config = ["dep:toml"]
example = ["config", "dep:tokio"]
binary = [
  "config",
  "dep:pkce",
  "dep:reqwest",
  "dep:tokio",
  "dep:url",
]


[[bin]]
name = "generate-token"
path = "src/bin/generate_token.rs"
required-features = ["binary"]

[[example]]
name = "dirigera"
required-features = ["example"]
